apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - command: ["npm", "run", "start"]
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: MONGO_DB
                  
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MONGO_URL
                  
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: NODE_ENV
                  
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: env
                  key: REDIS_URL
                  
          image: backend:latest
          imagePullPolicy: Never
          name: backend
          ports:
            - containerPort: 3000
